[server]
# How long (s) the interval the server pings the client to keep connection alive
# 1200 s = 20 minutes
websocketPingInterval = 1200
maxUploadSize = 200
headless = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true

[theme]
base = "dark"
