[server]
# Send a ping every 30 seconds to keep the Streamlit Cloud load balancer connection alive
websocketPingInterval = 30
# Allow the user to be completely idle for up to 30 minutes (1800s) before terminating the session
websocketPingTimeout = 1800
maxUploadSize = 200
headless = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true

[theme]
base = "dark"
